spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: store-auth
          uri: lb://store-auth
          predicates:
            - Path=/auth/**

        - id: store-account
          uri: lb://store-account
          predicates:
            - Path=/accounts/**

        - id: store-job
          uri: lb://store-job
          predicates:
            - Path=/jobs/**

        - id: store-inscricao
          uri: lb://store-inscricao
          predicates:
            - Path=/inscricoes/**

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/insper/**

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /jobs/actuator,
      ANY /inscricoes/actuator,
